#!/usr/bin/env bash

set -Eeuo pipefail
IFS=$'\n\t'

# shellcheck disable=SC1091 # functions.bash is not statically followable
source "${SCRIPTS_DIR}/functions.bash"
log::enable_err_trap
system::require_bash_version 4 0
args::check_no_args "$@"

function get_columns() {
  args::check_exactly_1_arg "$@"
  sed 's/[^,]//g' <<< "$1" | awk '{ print length }'
}

for csv_file in "$(misc::this_script_dir)/"*.csv; do
  expected_num_columns="$(get_columns "$(head --lines 1 "${csv_file}")")"
  while read -r line; do
    line_num_columns="$(get_columns "${line}")"
    if [[ "${line_num_columns}" != "${expected_num_columns}" ]]; then
      log::log "$(basename ${csv_file}) -- Expected ${expected_num_columns} columns; got ${line_num_columns} columns -- ${line}"
    fi
  done <<< "$(tail -n +2 "${csv_file}")"
done
